version: 2
registries:
  composer-repository-my-yoast-com:
    type: composer-repository
    url: https://my.yoast.com
    username: token
    password: "${{secrets.COMPOSER_REPOSITORY_MY_YOAST_COM_PASSWORD}}"

updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: wpackagist-plugin/elementor
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 3.1.3
    - 3.1.4
    - 3.2.0
    - 3.2.1
  - dependency-name: wpackagist-plugin/gutenberg
    versions:
    - 10.0.0
    - 10.0.1
    - 10.0.2
    - 10.1.0
    - 10.1.1
    - 10.2.0
    - 10.2.1
    - 10.3.1
    - 10.3.2
    - 10.4.0
    - 10.4.1
    - 9.8.2
    - 9.8.3
    - 9.9.0
    - 9.9.1
    - 9.9.2
    - 9.9.3
  - dependency-name: wpackagist-plugin/google-site-kit
    versions:
    - 1.24.0
    - 1.25.0
    - 1.26.0
    - 1.27.0
    - 1.28.0
    - 1.29.0
    - 1.30.0
  - dependency-name: wpackagist-plugin/wordpress-seo
    versions:
    - "15.7"
    - "15.8"
    - "15.9"
    - 15.9.1
    - 15.9.2
    - "16.0"
    - 16.0.1
    - 16.0.2
    - "16.1"
    - 16.1.1
  - dependency-name: wpackagist-plugin/ewww-image-optimizer
    versions:
    - 6.0.1
    - 6.0.3
    - 6.1.0
    - 6.1.1
  - dependency-name: roots/wordpress
    versions:
    - "5.6"
    - 5.6.1
    - 5.6.2
    - "5.7"
  - dependency-name: 10up/elasticpress
    versions:
    - 3.5.3
    - 3.5.4
    - 3.5.5
  - dependency-name: wpackagist-plugin/simple-history
    versions:
    - 2.38.0
    - 2.39.0
  - dependency-name: wpackagist-theme/twentytwenty
    versions:
    - "1.6"
  registries:
  - composer-repository-my-yoast-com
